// Code generated by goyacc -p assembler -o pkg/rv32iasm/assembler.y.go pkg/rv32iasm/assembler.y. DO NOT EDIT.

//line pkg/rv32iasm/assembler.y:2
package rv32iasm

import __yyfmt__ "fmt"

//line pkg/rv32iasm/assembler.y:2

import (
	"github.com/sokoide/rv32i-go/pkg/rv32i"
	"strconv"

	log "github.com/sirupsen/logrus"
)

func chkerr(err error) {
	if err != nil {
		panic(err)
	}
}

//line pkg/rv32iasm/assembler.y:17
type assemblerSymType struct {
	yys     int
	program *Program
	stmt    *statement
	expr    expression
	tok     token
}

const LF = 57346
const COLON = 57347
const COMMA = 57348
const LP = 57349
const RP = 57350
const NUMBER = 57351
const IDENT = 57352
const REGISTER = 57353
const AUIPC = 57354
const LUI = 57355
const JAL = 57356
const JALR = 57357
const RET = 57358
const BEQ = 57359
const BNE = 57360
const BLT = 57361
const BGE = 57362
const BLTU = 57363
const BGEU = 57364
const LW = 57365
const LBU = 57366
const SB = 57367
const SH = 57368
const SW = 57369
const ADDI = 57370
const LI = 57371
const SLTIU = 57372
const SEQZ = 57373
const ANDI = 57374
const SRLI = 57375
const ADD = 57376
const SUB = 57377

var assemblerToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LF",
	"COLON",
	"COMMA",
	"LP",
	"RP",
	"NUMBER",
	"IDENT",
	"REGISTER",
	"AUIPC",
	"LUI",
	"JAL",
	"JALR",
	"RET",
	"BEQ",
	"BNE",
	"BLT",
	"BGE",
	"BLTU",
	"BGEU",
	"LW",
	"LBU",
	"SB",
	"SH",
	"SW",
	"ADDI",
	"LI",
	"SLTIU",
	"SEQZ",
	"ANDI",
	"SRLI",
	"ADD",
	"SUB",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
}

var assemblerStatenames = [...]string{}

const assemblerEofCode = 1
const assemblerErrCode = 2
const assemblerInitialStackSize = 16

//line pkg/rv32iasm/assembler.y:420

//line yacctab:1
var assemblerExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 3,
}

const assemblerPrivate = 57344

const assemblerLast = 191

var assemblerAct = [...]uint8{
	54, 53, 28, 30, 29, 31, 32, 33, 34, 35,
	36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
	46, 47, 48, 49, 50, 51, 52, 66, 54, 65,
	175, 55, 57, 58, 59, 60, 177, 116, 57, 58,
	59, 60, 59, 60, 64, 63, 176, 171, 170, 169,
	168, 167, 160, 140, 139, 138, 137, 136, 87, 55,
	88, 89, 90, 91, 135, 133, 127, 126, 125, 124,
	123, 122, 121, 85, 84, 83, 82, 81, 80, 79,
	78, 77, 76, 75, 74, 73, 72, 71, 70, 69,
	68, 67, 62, 61, 174, 173, 172, 166, 165, 164,
	163, 162, 161, 134, 132, 131, 130, 129, 128, 120,
	119, 118, 117, 183, 182, 181, 180, 179, 178, 142,
	153, 152, 151, 150, 149, 141, 96, 159, 158, 157,
	156, 155, 154, 148, 147, 146, 145, 144, 143, 115,
	114, 113, 112, 111, 110, 109, 108, 107, 106, 105,
	104, 103, 102, 101, 100, 99, 98, 97, 95, 94,
	93, 92, 86, 56, 27, 26, 25, 22, 24, 23,
	21, 20, 19, 18, 17, 16, 15, 14, 13, 12,
	11, 10, 9, 8, 7, 6, 5, 4, 3, 2,
	1,
}

var assemblerPact = [...]int16{
	-1000, -9, 159, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 2, 82,
	81, 34, 18, -1000, 80, 79, 78, 77, 76, 75,
	74, 73, 72, 71, 70, 69, 68, 67, 66, 65,
	64, 63, 62, 157, -1000, 19, -1000, 19, 19, 19,
	19, 155, 154, 153, -1000, 152, 119, 151, 150, 149,
	148, 147, 146, 145, 144, 143, 142, 141, 140, 139,
	138, 137, 136, 135, 134, 133, -1000, -4, 4, 4,
	-1000, -1000, 103, 102, 101, 100, 61, 60, 59, 58,
	57, 56, 55, 99, 98, 97, 96, 95, 54, 94,
	53, 46, 45, 44, 43, 42, -1000, -1000, -1000, -1000,
	118, 111, 132, 131, 130, 129, 128, 127, 117, 116,
	115, 114, 113, 126, -1000, 125, -1000, 124, 123, 122,
	121, 41, -1000, 93, 92, 91, 90, 89, 88, 40,
	39, 38, 37, 36, 87, 86, 85, 21, 35, 25,
	110, -1000, -1000, -1000, -1000, -1000, -1000, 109, 108, 107,
	106, 105, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000,
}

var assemblerPgo = [...]uint8{
	0, 190, 189, 188, 187, 186, 185, 184, 183, 182,
	181, 180, 179, 178, 177, 176, 175, 174, 173, 172,
	171, 170, 169, 168, 167, 166, 165, 164, 2,
}

var assemblerR1 = [...]int8{
	0, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	3, 4, 5, 5, 6, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 24, 22, 23, 25, 26, 27, 28, 28, 28,
	28, 28, 28,
}

var assemblerR2 = [...]int8{
	0, 0, 3, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	4, 4, 4, 2, 7, 5, 1, 6, 6, 6,
	6, 6, 6, 7, 7, 7, 7, 7, 6, 4,
	6, 4, 6, 6, 6, 6, 2, 1, 3, 3,
	3, 3, 3,
}

var assemblerChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -11, -12, -13, -14, -15, -16, -17, -18, -19,
	-20, -21, -24, -22, -23, -25, -26, -27, -28, 13,
	12, 14, 15, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 10, 9, 40, 4, 36, 37, 38,
	39, 11, 11, 11, 10, 11, 9, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 5, -28, -28, -28,
	-28, -28, 6, 6, 6, 6, 7, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 41, 9, 9, 9,
	9, 11, 11, 11, 11, 11, 11, 11, 9, 9,
	9, 9, 9, 11, 9, 11, 11, 11, 11, 11,
	11, 7, 8, 6, 6, 6, 6, 6, 6, 7,
	7, 7, 7, 7, 6, 6, 6, 6, 6, 6,
	11, 9, 9, 9, 9, 9, 9, 11, 11, 11,
	11, 11, 9, 9, 9, 9, 11, 11, 8, 8,
	8, 8, 8, 8,
}

var assemblerDef = [...]int8{
	1, -2, 0, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 22, 23, 24, 25, 26, 27, 28, 29, 0,
	0, 0, 0, 36, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 57, 0, 2, 0, 0, 0,
	0, 0, 0, 0, 33, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 56, 0, 58, 59,
	60, 61, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 62, 30, 31, 32,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 49, 0, 51, 0, 0, 0,
	0, 0, 35, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 37, 38, 39, 40, 41, 42, 0, 0, 0,
	0, 0, 48, 50, 52, 53, 54, 55, 34, 43,
	44, 45, 46, 47,
}

var assemblerTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	40, 41, 38, 36, 3, 37, 3, 39,
}

var assemblerTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35,
}

var assemblerTok3 = [...]int8{
	0,
}

var assemblerErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	assemblerDebug        = 0
	assemblerErrorVerbose = false
)

type assemblerLexer interface {
	Lex(lval *assemblerSymType) int
	Error(s string)
}

type assemblerParser interface {
	Parse(assemblerLexer) int
	Lookahead() int
}

type assemblerParserImpl struct {
	lval  assemblerSymType
	stack [assemblerInitialStackSize]assemblerSymType
	char  int
}

func (p *assemblerParserImpl) Lookahead() int {
	return p.char
}

func assemblerNewParser() assemblerParser {
	return &assemblerParserImpl{}
}

const assemblerFlag = -1000

func assemblerTokname(c int) string {
	if c >= 1 && c-1 < len(assemblerToknames) {
		if assemblerToknames[c-1] != "" {
			return assemblerToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func assemblerStatname(s int) string {
	if s >= 0 && s < len(assemblerStatenames) {
		if assemblerStatenames[s] != "" {
			return assemblerStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func assemblerErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !assemblerErrorVerbose {
		return "syntax error"
	}

	for _, e := range assemblerErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + assemblerTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(assemblerPact[state])
	for tok := TOKSTART; tok-1 < len(assemblerToknames); tok++ {
		if n := base + tok; n >= 0 && n < assemblerLast && int(assemblerChk[int(assemblerAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if assemblerDef[state] == -2 {
		i := 0
		for assemblerExca[i] != -1 || int(assemblerExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; assemblerExca[i] >= 0; i += 2 {
			tok := int(assemblerExca[i])
			if tok < TOKSTART || assemblerExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if assemblerExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += assemblerTokname(tok)
	}
	return res
}

func assemblerlex1(lex assemblerLexer, lval *assemblerSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(assemblerTok1[0])
		goto out
	}
	if char < len(assemblerTok1) {
		token = int(assemblerTok1[char])
		goto out
	}
	if char >= assemblerPrivate {
		if char < assemblerPrivate+len(assemblerTok2) {
			token = int(assemblerTok2[char-assemblerPrivate])
			goto out
		}
	}
	for i := 0; i < len(assemblerTok3); i += 2 {
		token = int(assemblerTok3[i+0])
		if token == char {
			token = int(assemblerTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(assemblerTok2[1]) /* unknown char */
	}
	if assemblerDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", assemblerTokname(token), uint(char))
	}
	return char, token
}

func assemblerParse(assemblerlex assemblerLexer) int {
	return assemblerNewParser().Parse(assemblerlex)
}

func (assemblerrcvr *assemblerParserImpl) Parse(assemblerlex assemblerLexer) int {
	var assemblern int
	var assemblerVAL assemblerSymType
	var assemblerDollar []assemblerSymType
	_ = assemblerDollar // silence set and not used
	assemblerS := assemblerrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	assemblerstate := 0
	assemblerrcvr.char = -1
	assemblertoken := -1 // assemblerrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		assemblerstate = -1
		assemblerrcvr.char = -1
		assemblertoken = -1
	}()
	assemblerp := -1
	goto assemblerstack

ret0:
	return 0

ret1:
	return 1

assemblerstack:
	/* put a state and value onto the stack */
	if assemblerDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", assemblerTokname(assemblertoken), assemblerStatname(assemblerstate))
	}

	assemblerp++
	if assemblerp >= len(assemblerS) {
		nyys := make([]assemblerSymType, len(assemblerS)*2)
		copy(nyys, assemblerS)
		assemblerS = nyys
	}
	assemblerS[assemblerp] = assemblerVAL
	assemblerS[assemblerp].yys = assemblerstate

assemblernewstate:
	assemblern = int(assemblerPact[assemblerstate])
	if assemblern <= assemblerFlag {
		goto assemblerdefault /* simple state */
	}
	if assemblerrcvr.char < 0 {
		assemblerrcvr.char, assemblertoken = assemblerlex1(assemblerlex, &assemblerrcvr.lval)
	}
	assemblern += assemblertoken
	if assemblern < 0 || assemblern >= assemblerLast {
		goto assemblerdefault
	}
	assemblern = int(assemblerAct[assemblern])
	if int(assemblerChk[assemblern]) == assemblertoken { /* valid shift */
		assemblerrcvr.char = -1
		assemblertoken = -1
		assemblerVAL = assemblerrcvr.lval
		assemblerstate = assemblern
		if Errflag > 0 {
			Errflag--
		}
		goto assemblerstack
	}

assemblerdefault:
	/* default state action */
	assemblern = int(assemblerDef[assemblerstate])
	if assemblern == -2 {
		if assemblerrcvr.char < 0 {
			assemblerrcvr.char, assemblertoken = assemblerlex1(assemblerlex, &assemblerrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if assemblerExca[xi+0] == -1 && int(assemblerExca[xi+1]) == assemblerstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			assemblern = int(assemblerExca[xi+0])
			if assemblern < 0 || assemblern == assemblertoken {
				break
			}
		}
		assemblern = int(assemblerExca[xi+1])
		if assemblern < 0 {
			goto ret0
		}
	}
	if assemblern == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			assemblerlex.Error(assemblerErrorMessage(assemblerstate, assemblertoken))
			Nerrs++
			if assemblerDebug >= 1 {
				__yyfmt__.Printf("%s", assemblerStatname(assemblerstate))
				__yyfmt__.Printf(" saw %s\n", assemblerTokname(assemblertoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for assemblerp >= 0 {
				assemblern = int(assemblerPact[assemblerS[assemblerp].yys]) + assemblerErrCode
				if assemblern >= 0 && assemblern < assemblerLast {
					assemblerstate = int(assemblerAct[assemblern]) /* simulate a shift of "error" */
					if int(assemblerChk[assemblerstate]) == assemblerErrCode {
						goto assemblerstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if assemblerDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", assemblerS[assemblerp].yys)
				}
				assemblerp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if assemblerDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", assemblerTokname(assemblertoken))
			}
			if assemblertoken == assemblerEofCode {
				goto ret1
			}
			assemblerrcvr.char = -1
			assemblertoken = -1
			goto assemblernewstate /* try again in the same state */
		}
	}

	/* reduction by production assemblern */
	if assemblerDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", assemblern, assemblerStatname(assemblerstate))
	}

	assemblernt := assemblern
	assemblerpt := assemblerp
	_ = assemblerpt // guard against "declared and not used"

	assemblerp -= int(assemblerR2[assemblern])
	// assemblerp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if assemblerp+1 >= len(assemblerS) {
		nyys := make([]assemblerSymType, len(assemblerS)*2)
		copy(nyys, assemblerS)
		assemblerS = nyys
	}
	assemblerVAL = assemblerS[assemblerp+1]

	/* consult goto table to find next state */
	assemblern = int(assemblerR1[assemblern])
	assemblerg := int(assemblerPgo[assemblern])
	assemblerj := assemblerg + assemblerS[assemblerp].yys + 1

	if assemblerj >= assemblerLast {
		assemblerstate = int(assemblerAct[assemblerg])
	} else {
		assemblerstate = int(assemblerAct[assemblerj])
		if int(assemblerChk[assemblerstate]) != -assemblern {
			assemblerstate = int(assemblerAct[assemblerg])
		}
	}
	// dummy call; replaced with literal code
	switch assemblernt {

	case 1:
		assemblerDollar = assemblerS[assemblerpt-0 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:45
		{
			log.Debug("* empty program")
			assemblerVAL.program = &Program{
				statements: make([]*statement, 0),
			}
			assemblerlex.(*lexer).program = assemblerVAL.program
		}
	case 2:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:52
		{
			log.Debugf("* appendind stmt %v, stmt count %d", assemblerDollar[2].stmt, len(assemblerVAL.program.statements))
			assemblerVAL.program = &Program{
				statements: append(assemblerDollar[1].program.statements, assemblerDollar[2].stmt),
			}
			assemblerlex.(*lexer).program = assemblerVAL.program
		}
	case 3:
		assemblerDollar = assemblerS[assemblerpt-0 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:60
		{
			log.Debug("* comment or empty stmt")
			assemblerVAL.stmt = &statement{
				opcode: "comment",
			}
		}
	case 4:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:66
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 5:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:67
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 6:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:68
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 7:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:69
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 8:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:70
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 9:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:71
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 10:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:72
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 11:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:73
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 12:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:74
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 13:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:75
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 14:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:76
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 15:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:77
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 16:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:78
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 17:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:79
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 18:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:80
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 19:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:81
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 20:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:82
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 21:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:83
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 22:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:84
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 23:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:85
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 24:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:86
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 25:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:87
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 26:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:88
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 27:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:89
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 28:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:90
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 29:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:91
		{
			log.Debugf("* stmt expr %v", assemblerVAL.stmt)
			assemblerVAL.stmt = &statement{
				opcode: "expr",
			}
		}
	case 30:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:98
		{
			log.Debugf("* lui_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 31:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:109
		{
			log.Debugf("* auipc_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 32:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:120
		{
			log.Debugf("* jal_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 33:
		assemblerDollar = assemblerS[assemblerpt-2 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:130
		{
			log.Debugf("* jal_stmt (label): %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    1, // if rd is omitted, defaults to x1
				str1:   assemblerDollar[2].tok.lit,
			}
		}
	case 34:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:139
		{
			log.Debugf("* jalr_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 35:
		assemblerDollar = assemblerS[assemblerpt-5 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:150
		{
			log.Debugf("* jalr_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[2].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    1,
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[4].tok.lit],
			}
		}
	case 36:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:162
		{
			log.Debugf("* ret_stmt")
			assemblerVAL.stmt = &statement{
				opcode: "jalr",
				op1:    0,
				op2:    0,
				op3:    1,
			}
		}
	case 37:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:172
		{
			log.Debugf("* beq_stmt")
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: "beq",
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 38:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:184
		{
			log.Debugf("* bne_stmt")
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: "bne",
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 39:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:196
		{
			log.Debugf("* blt_stmt")
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: "blt",
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 40:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:208
		{
			log.Debugf("* bge_stmt")
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: "bge",
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 41:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:220
		{
			log.Debugf("* bltu_stmt")
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: "bltu",
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 42:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:232
		{
			log.Debugf("* bgeu_stmt")
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: "bgeu",
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 43:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:244
		{
			log.Debugf("* lw_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 44:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:256
		{
			log.Debugf("* lbu_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 45:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:268
		{
			log.Debugf("* sb_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 46:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:280
		{
			log.Debugf("* sh_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 47:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:292
		{
			log.Debugf("* sw_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 48:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:304
		{
			log.Debugf("* addi_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 49:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:316
		{
			log.Debugf("* li_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 50:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:327
		{
			log.Debugf("* sltiu_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 51:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:339
		{
			log.Debugf("* seqz_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
			}
		}
	case 52:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:348
		{
			log.Debugf("* andi_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 53:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:361
		{
			log.Debugf("* srli_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 54:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:373
		{
			log.Debugf("* add_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 55:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:383
		{
			log.Debugf("* sub_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 56:
		assemblerDollar = assemblerS[assemblerpt-2 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:393
		{
			log.Debugf("* label_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: "label",
				str1:   assemblerDollar[1].tok.lit,
			}
		}
	case 57:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:401
		{
			assemblerVAL.expr = &numberExpression{Lit: assemblerDollar[1].tok.lit}
		}
	case 58:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:404
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('+'), RHS: assemblerDollar[3].expr}
		}
	case 59:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:407
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('-'), RHS: assemblerDollar[3].expr}
		}
	case 60:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:410
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('*'), RHS: assemblerDollar[3].expr}
		}
	case 61:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:413
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('/'), RHS: assemblerDollar[3].expr}
		}
	case 62:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:416
		{
			assemblerVAL.expr = &parenExpression{SubExpr: assemblerDollar[2].expr}
		}
	}
	goto assemblerstack /* stack new state and value */
}
