// Code generated by goyacc -p assembler -o pkg/rv32iasm/assembler.y.go pkg/rv32iasm/assembler.y. DO NOT EDIT.

//line pkg/rv32iasm/assembler.y:2
package rv32iasm

import __yyfmt__ "fmt"

//line pkg/rv32iasm/assembler.y:2

import (
	log "github.com/sirupsen/logrus"
	"strconv"
)

func chkerr(err error) {
	if err != nil {
		panic(err)
	}
}

//line pkg/rv32iasm/assembler.y:15
type assemblerSymType struct {
	yys     int
	program *Program
	stmt    *statement
	expr    expression
	tok     token
}

const LF = 57346
const COLON = 57347
const COMMA = 57348
const LP = 57349
const RP = 57350
const NUMBER = 57351
const IDENT = 57352
const REGISTER = 57353
const AUIPC = 57354
const LUI = 57355
const JAL = 57356
const JALR = 57357
const RET = 57358
const LW = 57359
const SW = 57360
const ADDI = 57361
const LI = 57362
const SLTIU = 57363
const SEQZ = 57364
const ANDI = 57365
const SRLI = 57366
const ADD = 57367
const SUB = 57368

var assemblerToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LF",
	"COLON",
	"COMMA",
	"LP",
	"RP",
	"NUMBER",
	"IDENT",
	"REGISTER",
	"AUIPC",
	"LUI",
	"JAL",
	"JALR",
	"RET",
	"LW",
	"SW",
	"ADDI",
	"LI",
	"SLTIU",
	"SEQZ",
	"ANDI",
	"SRLI",
	"ADD",
	"SUB",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
}

var assemblerStatenames = [...]string{}

const assemblerEofCode = 1
const assemblerErrCode = 2
const assemblerInitialStackSize = 16

//line pkg/rv32iasm/assembler.y:285

//line yacctab:1
var assemblerExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 3,
}

const assemblerPrivate = 57344

const assemblerLast = 113

var assemblerAct = [...]int8{
	34, 33, 18, 20, 19, 21, 103, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 39, 40,
	44, 43, 35, 37, 38, 39, 40, 34, 74, 37,
	38, 39, 40, 102, 97, 96, 87, 86, 56, 85,
	57, 58, 59, 60, 84, 83, 82, 80, 54, 35,
	53, 52, 51, 50, 49, 48, 47, 46, 45, 42,
	41, 101, 100, 99, 98, 81, 79, 78, 77, 76,
	75, 105, 104, 89, 88, 95, 94, 93, 92, 91,
	90, 73, 72, 71, 70, 69, 68, 67, 66, 65,
	64, 63, 62, 61, 55, 36, 17, 16, 15, 12,
	14, 13, 11, 10, 9, 8, 7, 6, 5, 4,
	3, 2, 1,
}

var assemblerPact = [...]int16{
	-1000, -9, 91, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 2, 49,
	48, 10, -1000, 47, 46, 45, 44, 43, 42, 41,
	40, 39, 37, 89, -1000, 18, -1000, 18, 18, 18,
	18, 87, 86, 85, -1000, 84, 83, 82, 81, 80,
	79, 78, 77, 76, 75, -1000, -4, -11, -11, -1000,
	-1000, 61, 60, 59, 58, 57, 36, 56, 35, 34,
	33, 28, 26, 25, -1000, -1000, -1000, -1000, 67, 66,
	74, -1000, 73, -1000, 72, 71, 70, 69, 24, 23,
	55, 54, 53, 52, 22, -5, 64, 63, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000,
}

var assemblerPgo = [...]int8{
	0, 112, 111, 110, 109, 108, 108, 107, 106, 105,
	104, 103, 102, 101, 100, 99, 98, 97, 96, 2,
}

var assemblerR1 = [...]int8{
	0, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	3, 4, 5, 5, 6, 7, 8, 9, 10, 11,
	12, 15, 13, 14, 16, 17, 18, 19, 19, 19,
	19, 19, 19,
}

var assemblerR2 = [...]int8{
	0, 0, 3, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	4, 4, 4, 2, 7, 1, 7, 7, 6, 4,
	6, 4, 6, 6, 6, 6, 2, 1, 3, 3,
	3, 3, 3,
}

var assemblerChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -7, -8, -9, -10,
	-11, -12, -15, -13, -14, -16, -17, -18, -19, 13,
	12, 14, 16, 17, 18, 19, 20, 21, 22, 23,
	24, 25, 26, 10, 9, 31, 4, 27, 28, 29,
	30, 11, 11, 11, 10, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 5, -19, -19, -19, -19,
	-19, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 32, 9, 9, 9, 9, 9,
	11, 9, 11, 11, 11, 11, 11, 11, 7, 7,
	6, 6, 6, 6, 6, 6, 11, 11, 9, 9,
	9, 9, 11, 11, 8, 8,
}

var assemblerDef = [...]int8{
	1, -2, 0, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 0,
	0, 0, 25, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 37, 0, 2, 0, 0, 0,
	0, 0, 0, 0, 23, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 36, 0, 38, 39, 40,
	41, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 42, 20, 21, 22, 0, 0,
	0, 29, 0, 31, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 28, 30,
	32, 33, 34, 35, 26, 27,
}

var assemblerTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	31, 32, 29, 27, 3, 28, 3, 30,
}

var assemblerTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var assemblerTok3 = [...]int8{
	0,
}

var assemblerErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	assemblerDebug        = 0
	assemblerErrorVerbose = false
)

type assemblerLexer interface {
	Lex(lval *assemblerSymType) int
	Error(s string)
}

type assemblerParser interface {
	Parse(assemblerLexer) int
	Lookahead() int
}

type assemblerParserImpl struct {
	lval  assemblerSymType
	stack [assemblerInitialStackSize]assemblerSymType
	char  int
}

func (p *assemblerParserImpl) Lookahead() int {
	return p.char
}

func assemblerNewParser() assemblerParser {
	return &assemblerParserImpl{}
}

const assemblerFlag = -1000

func assemblerTokname(c int) string {
	if c >= 1 && c-1 < len(assemblerToknames) {
		if assemblerToknames[c-1] != "" {
			return assemblerToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func assemblerStatname(s int) string {
	if s >= 0 && s < len(assemblerStatenames) {
		if assemblerStatenames[s] != "" {
			return assemblerStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func assemblerErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !assemblerErrorVerbose {
		return "syntax error"
	}

	for _, e := range assemblerErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + assemblerTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(assemblerPact[state])
	for tok := TOKSTART; tok-1 < len(assemblerToknames); tok++ {
		if n := base + tok; n >= 0 && n < assemblerLast && int(assemblerChk[int(assemblerAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if assemblerDef[state] == -2 {
		i := 0
		for assemblerExca[i] != -1 || int(assemblerExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; assemblerExca[i] >= 0; i += 2 {
			tok := int(assemblerExca[i])
			if tok < TOKSTART || assemblerExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if assemblerExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += assemblerTokname(tok)
	}
	return res
}

func assemblerlex1(lex assemblerLexer, lval *assemblerSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(assemblerTok1[0])
		goto out
	}
	if char < len(assemblerTok1) {
		token = int(assemblerTok1[char])
		goto out
	}
	if char >= assemblerPrivate {
		if char < assemblerPrivate+len(assemblerTok2) {
			token = int(assemblerTok2[char-assemblerPrivate])
			goto out
		}
	}
	for i := 0; i < len(assemblerTok3); i += 2 {
		token = int(assemblerTok3[i+0])
		if token == char {
			token = int(assemblerTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(assemblerTok2[1]) /* unknown char */
	}
	if assemblerDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", assemblerTokname(token), uint(char))
	}
	return char, token
}

func assemblerParse(assemblerlex assemblerLexer) int {
	return assemblerNewParser().Parse(assemblerlex)
}

func (assemblerrcvr *assemblerParserImpl) Parse(assemblerlex assemblerLexer) int {
	var assemblern int
	var assemblerVAL assemblerSymType
	var assemblerDollar []assemblerSymType
	_ = assemblerDollar // silence set and not used
	assemblerS := assemblerrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	assemblerstate := 0
	assemblerrcvr.char = -1
	assemblertoken := -1 // assemblerrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		assemblerstate = -1
		assemblerrcvr.char = -1
		assemblertoken = -1
	}()
	assemblerp := -1
	goto assemblerstack

ret0:
	return 0

ret1:
	return 1

assemblerstack:
	/* put a state and value onto the stack */
	if assemblerDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", assemblerTokname(assemblertoken), assemblerStatname(assemblerstate))
	}

	assemblerp++
	if assemblerp >= len(assemblerS) {
		nyys := make([]assemblerSymType, len(assemblerS)*2)
		copy(nyys, assemblerS)
		assemblerS = nyys
	}
	assemblerS[assemblerp] = assemblerVAL
	assemblerS[assemblerp].yys = assemblerstate

assemblernewstate:
	assemblern = int(assemblerPact[assemblerstate])
	if assemblern <= assemblerFlag {
		goto assemblerdefault /* simple state */
	}
	if assemblerrcvr.char < 0 {
		assemblerrcvr.char, assemblertoken = assemblerlex1(assemblerlex, &assemblerrcvr.lval)
	}
	assemblern += assemblertoken
	if assemblern < 0 || assemblern >= assemblerLast {
		goto assemblerdefault
	}
	assemblern = int(assemblerAct[assemblern])
	if int(assemblerChk[assemblern]) == assemblertoken { /* valid shift */
		assemblerrcvr.char = -1
		assemblertoken = -1
		assemblerVAL = assemblerrcvr.lval
		assemblerstate = assemblern
		if Errflag > 0 {
			Errflag--
		}
		goto assemblerstack
	}

assemblerdefault:
	/* default state action */
	assemblern = int(assemblerDef[assemblerstate])
	if assemblern == -2 {
		if assemblerrcvr.char < 0 {
			assemblerrcvr.char, assemblertoken = assemblerlex1(assemblerlex, &assemblerrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if assemblerExca[xi+0] == -1 && int(assemblerExca[xi+1]) == assemblerstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			assemblern = int(assemblerExca[xi+0])
			if assemblern < 0 || assemblern == assemblertoken {
				break
			}
		}
		assemblern = int(assemblerExca[xi+1])
		if assemblern < 0 {
			goto ret0
		}
	}
	if assemblern == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			assemblerlex.Error(assemblerErrorMessage(assemblerstate, assemblertoken))
			Nerrs++
			if assemblerDebug >= 1 {
				__yyfmt__.Printf("%s", assemblerStatname(assemblerstate))
				__yyfmt__.Printf(" saw %s\n", assemblerTokname(assemblertoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for assemblerp >= 0 {
				assemblern = int(assemblerPact[assemblerS[assemblerp].yys]) + assemblerErrCode
				if assemblern >= 0 && assemblern < assemblerLast {
					assemblerstate = int(assemblerAct[assemblern]) /* simulate a shift of "error" */
					if int(assemblerChk[assemblerstate]) == assemblerErrCode {
						goto assemblerstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if assemblerDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", assemblerS[assemblerp].yys)
				}
				assemblerp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if assemblerDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", assemblerTokname(assemblertoken))
			}
			if assemblertoken == assemblerEofCode {
				goto ret1
			}
			assemblerrcvr.char = -1
			assemblertoken = -1
			goto assemblernewstate /* try again in the same state */
		}
	}

	/* reduction by production assemblern */
	if assemblerDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", assemblern, assemblerStatname(assemblerstate))
	}

	assemblernt := assemblern
	assemblerpt := assemblerp
	_ = assemblerpt // guard against "declared and not used"

	assemblerp -= int(assemblerR2[assemblern])
	// assemblerp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if assemblerp+1 >= len(assemblerS) {
		nyys := make([]assemblerSymType, len(assemblerS)*2)
		copy(nyys, assemblerS)
		assemblerS = nyys
	}
	assemblerVAL = assemblerS[assemblerp+1]

	/* consult goto table to find next state */
	assemblern = int(assemblerR1[assemblern])
	assemblerg := int(assemblerPgo[assemblern])
	assemblerj := assemblerg + assemblerS[assemblerp].yys + 1

	if assemblerj >= assemblerLast {
		assemblerstate = int(assemblerAct[assemblerg])
	} else {
		assemblerstate = int(assemblerAct[assemblerj])
		if int(assemblerChk[assemblerstate]) != -assemblern {
			assemblerstate = int(assemblerAct[assemblerg])
		}
	}
	// dummy call; replaced with literal code
	switch assemblernt {

	case 1:
		assemblerDollar = assemblerS[assemblerpt-0 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:40
		{
			log.Debug("* empty program")
			assemblerVAL.program = &Program{
				statements: make([]*statement, 0),
			}
			assemblerlex.(*lexer).program = assemblerVAL.program
		}
	case 2:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:47
		{
			log.Debugf("* appendind stmt %v, stmt count %d", assemblerDollar[2].stmt, len(assemblerVAL.program.statements))
			assemblerVAL.program = &Program{
				statements: append(assemblerDollar[1].program.statements, assemblerDollar[2].stmt),
			}
			assemblerlex.(*lexer).program = assemblerVAL.program
		}
	case 3:
		assemblerDollar = assemblerS[assemblerpt-0 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:55
		{
			log.Debug("* comment or empty stmt")
			assemblerVAL.stmt = &statement{
				opcode: "comment",
			}
		}
	case 4:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:61
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 5:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:62
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 6:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:63
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 7:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:64
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 8:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:65
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 9:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:66
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 10:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:67
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 11:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:68
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 12:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:69
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 13:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:70
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 14:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:71
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 15:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:72
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 16:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:73
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 17:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:74
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 18:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:75
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 19:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:76
		{
			log.Debugf("* stmt expr %v", assemblerVAL.stmt)
			assemblerVAL.stmt = &statement{
				opcode: "expr",
			}
		}
	case 20:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:83
		{
			log.Debugf("* lui_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 21:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:94
		{
			log.Debugf("* auipc_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 22:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:105
		{
			log.Debugf("* jal_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 23:
		assemblerDollar = assemblerS[assemblerpt-2 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:115
		{
			log.Debugf("* jal_stmt (label): %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				str1:   assemblerDollar[2].tok.lit,
			}
		}
	case 24:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:123
		{
			log.Debugf("* jalr_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    regs[assemblerDollar[6].tok.lit],
			}
		}
	case 25:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:135
		{
			log.Debugf("* ret_stmt")
			assemblerVAL.stmt = &statement{
				opcode: "jalr",
				op1:    0,
				op2:    0,
				op3:    1,
			}
		}
	case 26:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:145
		{
			log.Debugf("* lw_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    regs[assemblerDollar[6].tok.lit],
			}
		}
	case 27:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:157
		{
			log.Debugf("* sw_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    regs[assemblerDollar[6].tok.lit],
			}
		}
	case 28:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:169
		{
			log.Debugf("* addi_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 29:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:181
		{
			log.Debugf("* li_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 30:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:192
		{
			log.Debugf("* sltiu_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 31:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:204
		{
			log.Debugf("* seqz_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
			}
		}
	case 32:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:213
		{
			log.Debugf("* andi_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 33:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:226
		{
			log.Debugf("* srli_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 34:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:238
		{
			log.Debugf("* add_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
				op3:    regs[assemblerDollar[6].tok.lit],
			}
		}
	case 35:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:248
		{
			log.Debugf("* sub_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    regs[assemblerDollar[2].tok.lit],
				op2:    regs[assemblerDollar[4].tok.lit],
				op3:    regs[assemblerDollar[6].tok.lit],
			}
		}
	case 36:
		assemblerDollar = assemblerS[assemblerpt-2 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:258
		{
			log.Debugf("* label_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: "label",
				str1:   assemblerDollar[1].tok.lit,
			}
		}
	case 37:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:266
		{
			assemblerVAL.expr = &numberExpression{Lit: assemblerDollar[1].tok.lit}
		}
	case 38:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:269
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('+'), RHS: assemblerDollar[3].expr}
		}
	case 39:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:272
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('-'), RHS: assemblerDollar[3].expr}
		}
	case 40:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:275
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('*'), RHS: assemblerDollar[3].expr}
		}
	case 41:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:278
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('/'), RHS: assemblerDollar[3].expr}
		}
	case 42:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:281
		{
			assemblerVAL.expr = &parenExpression{SubExpr: assemblerDollar[2].expr}
		}
	}
	goto assemblerstack /* stack new state and value */
}
