// Code generated by goyacc -p assembler -o pkg/rv32iasm/assembler.y.go pkg/rv32iasm/assembler.y. DO NOT EDIT.

//line pkg/rv32iasm/assembler.y:2
package rv32iasm

import __yyfmt__ "fmt"

//line pkg/rv32iasm/assembler.y:2

import (
	"github.com/sokoide/rv32i-go/pkg/rv32i"
	"strconv"

	log "github.com/sirupsen/logrus"
)

func chkerr(err error) {
	if err != nil {
		panic(err)
	}
}

//line pkg/rv32iasm/assembler.y:17
type assemblerSymType struct {
	yys     int
	program *Program
	stmt    *statement
	expr    expression
	tok     token
}

const LF = 57346
const COLON = 57347
const COMMA = 57348
const LP = 57349
const RP = 57350
const NUMBER = 57351
const IDENT = 57352
const REGISTER = 57353
const AUIPC = 57354
const LUI = 57355
const JAL = 57356
const JALR = 57357
const RET = 57358
const LW = 57359
const LBU = 57360
const SB = 57361
const SH = 57362
const SW = 57363
const ADDI = 57364
const LI = 57365
const SLTIU = 57366
const SEQZ = 57367
const ANDI = 57368
const SRLI = 57369
const ADD = 57370
const SUB = 57371

var assemblerToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LF",
	"COLON",
	"COMMA",
	"LP",
	"RP",
	"NUMBER",
	"IDENT",
	"REGISTER",
	"AUIPC",
	"LUI",
	"JAL",
	"JALR",
	"RET",
	"LW",
	"LBU",
	"SB",
	"SH",
	"SW",
	"ADDI",
	"LI",
	"SLTIU",
	"SEQZ",
	"ANDI",
	"SRLI",
	"ADD",
	"SUB",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
}

var assemblerStatenames = [...]string{}

const assemblerEofCode = 1
const assemblerErrCode = 2
const assemblerInitialStackSize = 16

//line pkg/rv32iasm/assembler.y:339

//line yacctab:1
var assemblerExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 3,
}

const assemblerPrivate = 57344

const assemblerLast = 149

var assemblerAct = [...]uint8{
	42, 41, 22, 24, 23, 25, 26, 27, 28, 29,
	30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
	40, 54, 42, 53, 133, 43, 45, 46, 47, 48,
	135, 92, 45, 46, 47, 48, 47, 48, 52, 51,
	134, 129, 128, 127, 126, 125, 69, 43, 70, 71,
	72, 73, 124, 110, 109, 108, 107, 106, 105, 103,
	97, 67, 66, 65, 64, 63, 62, 61, 60, 59,
	58, 57, 56, 55, 50, 49, 132, 131, 130, 104,
	102, 101, 100, 99, 98, 96, 95, 94, 93, 141,
	140, 139, 138, 137, 136, 112, 117, 116, 115, 114,
	113, 111, 78, 123, 122, 121, 120, 119, 118, 91,
	90, 89, 88, 87, 86, 85, 84, 83, 82, 81,
	80, 79, 77, 76, 75, 74, 68, 44, 21, 20,
	19, 16, 18, 17, 15, 14, 13, 12, 11, 10,
	9, 8, 7, 6, 5, 4, 3, 2, 1,
}

var assemblerPact = [...]int16{
	-1000, -9, 123, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 2, 64, 63, 28, 12, -1000, 62, 61,
	60, 59, 58, 57, 56, 55, 54, 53, 52, 51,
	50, 121, -1000, 13, -1000, 13, 13, 13, 13, 119,
	118, 117, -1000, 116, 95, 115, 114, 113, 112, 111,
	110, 109, 108, 107, 106, 105, 104, 103, -1000, -4,
	4, 4, -1000, -1000, 79, 78, 77, 76, 49, 75,
	74, 73, 72, 71, 48, 70, 47, 46, 45, 44,
	43, 42, -1000, -1000, -1000, -1000, 94, 87, 93, 92,
	91, 90, 89, 102, -1000, 101, -1000, 100, 99, 98,
	97, 41, -1000, 34, 33, 32, 31, 30, 69, 68,
	67, 15, 29, 19, 86, 85, 84, 83, 82, 81,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000,
}

var assemblerPgo = [...]uint8{
	0, 148, 147, 146, 145, 144, 143, 142, 141, 140,
	139, 138, 137, 136, 135, 134, 133, 132, 131, 130,
	129, 128, 2,
}

var assemblerR1 = [...]int8{
	0, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 3, 4, 5, 5, 6, 6,
	7, 8, 9, 10, 11, 12, 13, 14, 15, 18,
	16, 17, 19, 20, 21, 22, 22, 22, 22, 22,
	22,
}

var assemblerR2 = [...]int8{
	0, 0, 3, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 4, 4, 4, 2, 7, 5,
	1, 7, 7, 7, 7, 7, 6, 4, 6, 4,
	6, 6, 6, 6, 2, 1, 3, 3, 3, 3,
	3,
}

var assemblerChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -11, -12, -13, -14, -15, -18, -16, -17, -19,
	-20, -21, -22, 13, 12, 14, 15, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 10, 9, 34, 4, 30, 31, 32, 33, 11,
	11, 11, 10, 11, 9, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 5, -22,
	-22, -22, -22, -22, 6, 6, 6, 6, 7, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 35, 9, 9, 9, 9, 11, 9, 9,
	9, 9, 9, 11, 9, 11, 11, 11, 11, 11,
	11, 7, 8, 7, 7, 7, 7, 7, 6, 6,
	6, 6, 6, 6, 11, 11, 11, 11, 11, 11,
	9, 9, 9, 9, 11, 11, 8, 8, 8, 8,
	8, 8,
}

var assemblerDef = [...]int8{
	1, -2, 0, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 22, 23, 0, 0, 0, 0, 30, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 45, 0, 2, 0, 0, 0, 0, 0,
	0, 0, 27, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 44, 0,
	46, 47, 48, 49, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 50, 24, 25, 26, 0, 0, 0, 0,
	0, 0, 0, 0, 37, 0, 39, 0, 0, 0,
	0, 0, 29, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	36, 38, 40, 41, 42, 43, 28, 31, 32, 33,
	34, 35,
}

var assemblerTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	34, 35, 32, 30, 3, 31, 3, 33,
}

var assemblerTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29,
}

var assemblerTok3 = [...]int8{
	0,
}

var assemblerErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	assemblerDebug        = 0
	assemblerErrorVerbose = false
)

type assemblerLexer interface {
	Lex(lval *assemblerSymType) int
	Error(s string)
}

type assemblerParser interface {
	Parse(assemblerLexer) int
	Lookahead() int
}

type assemblerParserImpl struct {
	lval  assemblerSymType
	stack [assemblerInitialStackSize]assemblerSymType
	char  int
}

func (p *assemblerParserImpl) Lookahead() int {
	return p.char
}

func assemblerNewParser() assemblerParser {
	return &assemblerParserImpl{}
}

const assemblerFlag = -1000

func assemblerTokname(c int) string {
	if c >= 1 && c-1 < len(assemblerToknames) {
		if assemblerToknames[c-1] != "" {
			return assemblerToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func assemblerStatname(s int) string {
	if s >= 0 && s < len(assemblerStatenames) {
		if assemblerStatenames[s] != "" {
			return assemblerStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func assemblerErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !assemblerErrorVerbose {
		return "syntax error"
	}

	for _, e := range assemblerErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + assemblerTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(assemblerPact[state])
	for tok := TOKSTART; tok-1 < len(assemblerToknames); tok++ {
		if n := base + tok; n >= 0 && n < assemblerLast && int(assemblerChk[int(assemblerAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if assemblerDef[state] == -2 {
		i := 0
		for assemblerExca[i] != -1 || int(assemblerExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; assemblerExca[i] >= 0; i += 2 {
			tok := int(assemblerExca[i])
			if tok < TOKSTART || assemblerExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if assemblerExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += assemblerTokname(tok)
	}
	return res
}

func assemblerlex1(lex assemblerLexer, lval *assemblerSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(assemblerTok1[0])
		goto out
	}
	if char < len(assemblerTok1) {
		token = int(assemblerTok1[char])
		goto out
	}
	if char >= assemblerPrivate {
		if char < assemblerPrivate+len(assemblerTok2) {
			token = int(assemblerTok2[char-assemblerPrivate])
			goto out
		}
	}
	for i := 0; i < len(assemblerTok3); i += 2 {
		token = int(assemblerTok3[i+0])
		if token == char {
			token = int(assemblerTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(assemblerTok2[1]) /* unknown char */
	}
	if assemblerDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", assemblerTokname(token), uint(char))
	}
	return char, token
}

func assemblerParse(assemblerlex assemblerLexer) int {
	return assemblerNewParser().Parse(assemblerlex)
}

func (assemblerrcvr *assemblerParserImpl) Parse(assemblerlex assemblerLexer) int {
	var assemblern int
	var assemblerVAL assemblerSymType
	var assemblerDollar []assemblerSymType
	_ = assemblerDollar // silence set and not used
	assemblerS := assemblerrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	assemblerstate := 0
	assemblerrcvr.char = -1
	assemblertoken := -1 // assemblerrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		assemblerstate = -1
		assemblerrcvr.char = -1
		assemblertoken = -1
	}()
	assemblerp := -1
	goto assemblerstack

ret0:
	return 0

ret1:
	return 1

assemblerstack:
	/* put a state and value onto the stack */
	if assemblerDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", assemblerTokname(assemblertoken), assemblerStatname(assemblerstate))
	}

	assemblerp++
	if assemblerp >= len(assemblerS) {
		nyys := make([]assemblerSymType, len(assemblerS)*2)
		copy(nyys, assemblerS)
		assemblerS = nyys
	}
	assemblerS[assemblerp] = assemblerVAL
	assemblerS[assemblerp].yys = assemblerstate

assemblernewstate:
	assemblern = int(assemblerPact[assemblerstate])
	if assemblern <= assemblerFlag {
		goto assemblerdefault /* simple state */
	}
	if assemblerrcvr.char < 0 {
		assemblerrcvr.char, assemblertoken = assemblerlex1(assemblerlex, &assemblerrcvr.lval)
	}
	assemblern += assemblertoken
	if assemblern < 0 || assemblern >= assemblerLast {
		goto assemblerdefault
	}
	assemblern = int(assemblerAct[assemblern])
	if int(assemblerChk[assemblern]) == assemblertoken { /* valid shift */
		assemblerrcvr.char = -1
		assemblertoken = -1
		assemblerVAL = assemblerrcvr.lval
		assemblerstate = assemblern
		if Errflag > 0 {
			Errflag--
		}
		goto assemblerstack
	}

assemblerdefault:
	/* default state action */
	assemblern = int(assemblerDef[assemblerstate])
	if assemblern == -2 {
		if assemblerrcvr.char < 0 {
			assemblerrcvr.char, assemblertoken = assemblerlex1(assemblerlex, &assemblerrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if assemblerExca[xi+0] == -1 && int(assemblerExca[xi+1]) == assemblerstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			assemblern = int(assemblerExca[xi+0])
			if assemblern < 0 || assemblern == assemblertoken {
				break
			}
		}
		assemblern = int(assemblerExca[xi+1])
		if assemblern < 0 {
			goto ret0
		}
	}
	if assemblern == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			assemblerlex.Error(assemblerErrorMessage(assemblerstate, assemblertoken))
			Nerrs++
			if assemblerDebug >= 1 {
				__yyfmt__.Printf("%s", assemblerStatname(assemblerstate))
				__yyfmt__.Printf(" saw %s\n", assemblerTokname(assemblertoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for assemblerp >= 0 {
				assemblern = int(assemblerPact[assemblerS[assemblerp].yys]) + assemblerErrCode
				if assemblern >= 0 && assemblern < assemblerLast {
					assemblerstate = int(assemblerAct[assemblern]) /* simulate a shift of "error" */
					if int(assemblerChk[assemblerstate]) == assemblerErrCode {
						goto assemblerstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if assemblerDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", assemblerS[assemblerp].yys)
				}
				assemblerp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if assemblerDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", assemblerTokname(assemblertoken))
			}
			if assemblertoken == assemblerEofCode {
				goto ret1
			}
			assemblerrcvr.char = -1
			assemblertoken = -1
			goto assemblernewstate /* try again in the same state */
		}
	}

	/* reduction by production assemblern */
	if assemblerDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", assemblern, assemblerStatname(assemblerstate))
	}

	assemblernt := assemblern
	assemblerpt := assemblerp
	_ = assemblerpt // guard against "declared and not used"

	assemblerp -= int(assemblerR2[assemblern])
	// assemblerp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if assemblerp+1 >= len(assemblerS) {
		nyys := make([]assemblerSymType, len(assemblerS)*2)
		copy(nyys, assemblerS)
		assemblerS = nyys
	}
	assemblerVAL = assemblerS[assemblerp+1]

	/* consult goto table to find next state */
	assemblern = int(assemblerR1[assemblern])
	assemblerg := int(assemblerPgo[assemblern])
	assemblerj := assemblerg + assemblerS[assemblerp].yys + 1

	if assemblerj >= assemblerLast {
		assemblerstate = int(assemblerAct[assemblerg])
	} else {
		assemblerstate = int(assemblerAct[assemblerj])
		if int(assemblerChk[assemblerstate]) != -assemblern {
			assemblerstate = int(assemblerAct[assemblerg])
		}
	}
	// dummy call; replaced with literal code
	switch assemblernt {

	case 1:
		assemblerDollar = assemblerS[assemblerpt-0 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:42
		{
			log.Debug("* empty program")
			assemblerVAL.program = &Program{
				statements: make([]*statement, 0),
			}
			assemblerlex.(*lexer).program = assemblerVAL.program
		}
	case 2:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:49
		{
			log.Debugf("* appendind stmt %v, stmt count %d", assemblerDollar[2].stmt, len(assemblerVAL.program.statements))
			assemblerVAL.program = &Program{
				statements: append(assemblerDollar[1].program.statements, assemblerDollar[2].stmt),
			}
			assemblerlex.(*lexer).program = assemblerVAL.program
		}
	case 3:
		assemblerDollar = assemblerS[assemblerpt-0 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:57
		{
			log.Debug("* comment or empty stmt")
			assemblerVAL.stmt = &statement{
				opcode: "comment",
			}
		}
	case 4:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:63
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 5:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:64
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 6:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:65
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 7:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:66
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 8:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:67
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 9:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:68
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 10:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:69
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 11:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:70
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 12:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:71
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 13:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:72
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 14:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:73
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 15:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:74
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 16:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:75
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 17:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:76
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 18:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:77
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 19:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:78
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 20:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:79
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 21:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:80
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 22:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:81
		{
			assemblerVAL.stmt = assemblerDollar[1].stmt
		}
	case 23:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:82
		{
			log.Debugf("* stmt expr %v", assemblerVAL.stmt)
			assemblerVAL.stmt = &statement{
				opcode: "expr",
			}
		}
	case 24:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:89
		{
			log.Debugf("* lui_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 25:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:100
		{
			log.Debugf("* auipc_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 26:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:111
		{
			log.Debugf("* jal_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 27:
		assemblerDollar = assemblerS[assemblerpt-2 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:121
		{
			log.Debugf("* jal_stmt (label): %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    1, // if rd is omitted, defaults to x1
				str1:   assemblerDollar[2].tok.lit,
			}
		}
	case 28:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:130
		{
			log.Debugf("* jalr_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 29:
		assemblerDollar = assemblerS[assemblerpt-5 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:141
		{
			log.Debugf("* jalr_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[2].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    1,
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[4].tok.lit],
			}
		}
	case 30:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:153
		{
			log.Debugf("* ret_stmt")
			assemblerVAL.stmt = &statement{
				opcode: "jalr",
				op1:    0,
				op2:    0,
				op3:    1,
			}
		}
	case 31:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:163
		{
			log.Debugf("* lw_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 32:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:175
		{
			log.Debugf("* lbu_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 33:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:187
		{
			log.Debugf("* sb_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 34:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:199
		{
			log.Debugf("* sh_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 35:
		assemblerDollar = assemblerS[assemblerpt-7 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:211
		{
			log.Debugf("* sw_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 36:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:223
		{
			log.Debugf("* addi_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 37:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:235
		{
			log.Debugf("* li_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[4].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    val,
			}
		}
	case 38:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:246
		{
			log.Debugf("* sltiu_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 39:
		assemblerDollar = assemblerS[assemblerpt-4 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:258
		{
			log.Debugf("* seqz_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
			}
		}
	case 40:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:267
		{
			log.Debugf("* andi_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 41:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:280
		{
			log.Debugf("* srli_stmt: %+v", assemblerDollar[1].tok)
			val, err := strconv.Atoi(assemblerDollar[6].tok.lit)
			chkerr(err)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    val,
			}
		}
	case 42:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:292
		{
			log.Debugf("* add_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 43:
		assemblerDollar = assemblerS[assemblerpt-6 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:302
		{
			log.Debugf("* sub_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: assemblerDollar[1].tok.lit,
				op1:    rv32i.Regs[assemblerDollar[2].tok.lit],
				op2:    rv32i.Regs[assemblerDollar[4].tok.lit],
				op3:    rv32i.Regs[assemblerDollar[6].tok.lit],
			}
		}
	case 44:
		assemblerDollar = assemblerS[assemblerpt-2 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:312
		{
			log.Debugf("* label_stmt: %+v", assemblerDollar[1].tok)
			assemblerVAL.stmt = &statement{
				opcode: "label",
				str1:   assemblerDollar[1].tok.lit,
			}
		}
	case 45:
		assemblerDollar = assemblerS[assemblerpt-1 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:320
		{
			assemblerVAL.expr = &numberExpression{Lit: assemblerDollar[1].tok.lit}
		}
	case 46:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:323
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('+'), RHS: assemblerDollar[3].expr}
		}
	case 47:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:326
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('-'), RHS: assemblerDollar[3].expr}
		}
	case 48:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:329
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('*'), RHS: assemblerDollar[3].expr}
		}
	case 49:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:332
		{
			assemblerVAL.expr = &binOpExpression{LHS: assemblerDollar[1].expr, Operator: int('/'), RHS: assemblerDollar[3].expr}
		}
	case 50:
		assemblerDollar = assemblerS[assemblerpt-3 : assemblerpt+1]
//line pkg/rv32iasm/assembler.y:335
		{
			assemblerVAL.expr = &parenExpression{SubExpr: assemblerDollar[2].expr}
		}
	}
	goto assemblerstack /* stack new state and value */
}
