// Code generated by "stringer -type OpName"; DO NOT EDIT.

package rv32i

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpLui-0]
	_ = x[OpAuipc-1]
	_ = x[OpJal-2]
	_ = x[OpJalr-3]
	_ = x[OpBeq-4]
	_ = x[OpBne-5]
	_ = x[OpBlt-6]
	_ = x[OpBge-7]
	_ = x[OpBltu-8]
	_ = x[OpBgeu-9]
	_ = x[OpLb-10]
	_ = x[OpLh-11]
	_ = x[OpLw-12]
	_ = x[OpLbu-13]
	_ = x[OpLhu-14]
	_ = x[OpSb-15]
	_ = x[OpSh-16]
	_ = x[OpSw-17]
	_ = x[OpAddi-18]
	_ = x[OpSlti-19]
	_ = x[OpSltiu-20]
	_ = x[OpXori-21]
	_ = x[OpOri-22]
	_ = x[OpAndi-23]
	_ = x[OpSlli-24]
	_ = x[OpSrli-25]
	_ = x[OpSrai-26]
	_ = x[OpAdd-27]
	_ = x[OpSub-28]
	_ = x[OpSll-29]
	_ = x[OpSlt-30]
	_ = x[OpSltu-31]
	_ = x[OpXor-32]
	_ = x[OpSrl-33]
	_ = x[OpSra-34]
	_ = x[OpOr-35]
	_ = x[OpAnd-36]
	_ = x[OpFence-37]
	_ = x[OpFenceI-38]
	_ = x[OpEcall-39]
	_ = x[OpEbreak-40]
	_ = x[OpCsrrw-41]
	_ = x[OpCsrrs-42]
	_ = x[OpCsrrc-43]
	_ = x[OpCsrrwi-44]
	_ = x[OpCsrrsi-45]
	_ = x[OpCsrrci-46]
}

const _OpName_name = "OpLuiOpAuipcOpJalOpJalrOpBeqOpBneOpBltOpBgeOpBltuOpBgeuOpLbOpLhOpLwOpLbuOpLhuOpSbOpShOpSwOpAddiOpSltiOpSltiuOpXoriOpOriOpAndiOpSlliOpSrliOpSraiOpAddOpSubOpSllOpSltOpSltuOpXorOpSrlOpSraOpOrOpAndOpFenceOpFenceIOpEcallOpEbreakOpCsrrwOpCsrrsOpCsrrcOpCsrrwiOpCsrrsiOpCsrrci"

var _OpName_index = [...]uint16{0, 5, 12, 17, 23, 28, 33, 38, 43, 49, 55, 59, 63, 67, 72, 77, 81, 85, 89, 95, 101, 108, 114, 119, 125, 131, 137, 143, 148, 153, 158, 163, 169, 174, 179, 184, 188, 193, 200, 208, 215, 223, 230, 237, 244, 252, 260, 268}

func (i OpName) String() string {
	if i < 0 || i >= OpName(len(_OpName_index)-1) {
		return "OpName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpName_name[_OpName_index[i]:_OpName_index[i+1]]
}
